### PR TITLE
Removed IE paradox, fixed bugs, & reduced size

### PR DESCRIPTION
**Pull request by anonyco**
Below is a summary of my changes.
<ol>
<li>

The use of plain `querySelectorAll` [in the core](https://github.com/frqnck/apt.js/blob/master/src/apt-core.js#L27) condemns your library to only function [in Internet Explorer version 9 and later](https://caniuse.com/#feat=queryselector) versions. Plain old `XMLHttpRequest` works just fine in [Internet Explorer 7 and later](https://caniuse.com/#feat=mdn-api_xmlhttprequest). Thus, it is a waste of space to include a fallback for unsupported browsers such as Internet Explorer 6 and earlier.</li>
<li>

Additionally, checking `xhrInstance.status` to be non-zero does not work in local files in Mozilla Firefox where the status is always zero even after the request has been completed.</li>
<li>

Next, the third parameter to XMLHttpRequest.prototype.open is optional: if left out, then this third parameter defaults to true and the HTTP request is asynchronous.</li>
<li>

Next, I fixed some nasty asynchronous UB (the worst kind of Undefined Behavior) whereby the `parse` method would never get added to `xhrInstance` if there is no `callback`. One cannot make the assumption that `parse` will never be used because, on line 28, `xhrInstance` is leaked back to the parent function where it can be utilized further and potentially use the `parse` method in the future.</li>
<li>

Note that the 3xx is a very valid and very important range of successful codes. The most common code in this range is 304 which indicates that the resource has not been changed since the last request made.</li>
<li>

I also want to clarify that my changes are with the goal in mind of minimal file size *regardless of performance*. Your original code and this new code both sacrifice much performance for the sake of file size.</li>
<li>

Also, it is better to use `response` instead of `responseText` in case if the parent function sets `xhrInstance.responseType` to something else other than text such as is seen below.

```javascript
$.ajax("binaryFile.raw", function(buffer) {
    // ...
}).responseType = "arraybuffer";
```

</li>
<li>

Lastly, I just want to suggest using clearer variable names. Using short tiny variables names makes the code harder for most people to read and does not reduce the minified file size.</li>
</ol>

I like the concept behind APT.js and I hope that this major rehaul of the HTTP API will make APT.js a bit smaller and a bit more reliable.

### CODE REVIEW

**Comment by frqnck** [comment]
Hi @anonyco, first many thanks for your contribution.

I have installed BrowserStack+Travis CI for automated testing of this project in order to ease refactoring and integrating pull requests just like yours. This works against numerous version of popular Web browsers, including IE8 (IE7 could be added too).

Currently, it seems there is an issue with `apt-ajax.js` hanging on IE9, 10, 11 and Safari 6.2 which your changes may actually fix. The ajax module use to work in the past and pass on these browsers so I suspect I must have broken it while refactoring it to release on Github. I must admit, I hardly did any testing on IE when I prepared this package – using BrowserStack here will change that.

I agree to most of your points and admire your dexterity here – pretty cool stuff.

Thanks again.

**Comment by frqnck** [comment]
PS could you resubmit yout PR so it is run against BrowserStack. Thanks.

**Comment by anonyco** [comment]
After resubmitting my pull request, Travis-CI errored about not providing the username:

```
Using config: /home/travis/build/frqnck/apt.js/browserstack.json
Error: Configuration parameter username is required.
```

Unfortunately, I am not very familiar with either Travis-CI or BrowserStack as I do not use build systems for my projects. So, there is not much help that I can offer. If you need me to resubmit my pull request again to test your fixes, then I would be happy to.

Also, I regret to inform you that although IE8 may appear to look supported, IE8 is in fact only partially supported by your library. IE8 partially implemented querySelector with only the basic CSS filters. So, `input.className` will work, but `input.className:checked` will not work in IE8. Anyways, [Windows XP supported ended in 2014](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-windows-xp-support), so there is no longer any need to support Internet Explorer version 10 and earlier.

~ Happy Coding!

**Comment by frqnck** [comment]
I have remove IE8 from the test matrix.

Please could you resubmit this PR hopefully it should work now.

**Comment by anonyco** [comment]
I just resubmitted my pull request again and it still gives the same error &#x1F641;

```
Using config: /home/travis/build/frqnck/apt.js/browserstack.json
Error: Configuration parameter username is required.
```
Please let me know when you are ready to try again.

~ Happy coding and good luck with :heart: from :dog:!
<sup>(I always try to focus on the positive things and dogs are always positive! I love dogs!)</sup>

**Comment by anonyco** [comment]
Also, I was just curious about what "most" means. Which of my changes do you disagree with? I would be fine with reverting them.

**Comment by frqnck** [comment]
Ha, this is a PR from a fork so it won’t work as explain there: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

I will merge this for now.

**Pull request merged**
